/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutComponentRouteImport } from './routes/checkout-component'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ForBusinessRouteImport } from './routes/for-business'
import { Route as ForCouriersRouteImport } from './routes/for-couriers'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as AuthenticatedCourierRouteImport } from './routes/_authenticated/courier'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeveloperDashboardRouteImport } from './routes/_authenticated/developer-dashboard'
import { Route as AuthenticatedMyAddressesRouteImport } from './routes/_authenticated/my-addresses'
import { Route as AuthenticatedMyCorrectionsRouteImport } from './routes/_authenticated/my-corrections'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as ACodeRouteImport } from './routes/a.$code'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'
import { Route as AdminCorrectionsRouteImport } from './routes/admin.corrections'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminQualityRouteImport } from './routes/admin.quality'
import { Route as BusinessIdRouteImport } from './routes/business.$id'
import { Route as ClaimIdRouteImport } from './routes/claim.$id'
import { Route as DCodeRouteImport } from './routes/d.$code'
import { Route as ECodeRouteImport } from './routes/e.$code'
import { Route as EmbedAddressRouteImport } from './routes/embed.address'
import { Route as NavigationCodeRouteImport } from './routes/navigation.$code'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api.public.checkout'
import { Route as ApiPublicResolveRouteImport } from './routes/api.public.resolve'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api.public.v1.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutComponentRoute = CheckoutComponentRouteImport.update({
  id: '/checkout-component',
  path: '/checkout-component',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBusinessRoute = ForBusinessRouteImport.update({
  id: '/for-business',
  path: '/for-business',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCouriersRoute = ForCouriersRouteImport.update({
  id: '/for-couriers',
  path: '/for-couriers',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCourierRoute = AuthenticatedCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperDashboardRoute =
  AuthenticatedDeveloperDashboardRouteImport.update({
    id: '/developer-dashboard',
    path: '/developer-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAddressesRoute =
  AuthenticatedMyAddressesRouteImport.update({
    id: '/my-addresses',
    path: '/my-addresses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyCorrectionsRoute =
  AuthenticatedMyCorrectionsRouteImport.update({
    id: '/my-corrections',
    path: '/my-corrections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ACodeRoute = ACodeRouteImport.update({
  id: '/a/$code',
  path: '/a/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/admin/claims',
  path: '/admin/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCorrectionsRoute = AdminCorrectionsRouteImport.update({
  id: '/admin/corrections',
  path: '/admin/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/admin/navigation',
  path: '/admin/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQualityRoute = AdminQualityRouteImport.update({
  id: '/admin/quality',
  path: '/admin/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIdRoute = ClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DCodeRoute = DCodeRouteImport.update({
  id: '/d/$code',
  path: '/d/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ECodeRoute = ECodeRouteImport.update({
  id: '/e/$code',
  path: '/e/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedAddressRoute = EmbedAddressRouteImport.update({
  id: '/embed/address',
  path: '/embed/address',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationCodeRoute = NavigationCodeRouteImport.update({
  id: '/navigation/$code',
  path: '/navigation/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResolveRoute = ApiPublicResolveRouteImport.update({
  id: '/api/public/resolve',
  path: '/api/public/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/checkout-component': typeof CheckoutComponentRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/for-business': typeof ForBusinessRoute
  '/for-couriers': typeof ForCouriersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/offline': typeof OfflineRoute
  '/places': typeof PlacesRoute
  '/plans': typeof PlansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/widget': typeof WidgetRoute
  '/courier': typeof AuthenticatedCourierRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer-dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/my-addresses': typeof AuthenticatedMyAddressesRoute
  '/my-corrections': typeof AuthenticatedMyCorrectionsRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/a/$code': typeof ACodeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/corrections': typeof AdminCorrectionsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/quality': typeof AdminQualityRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$id': typeof ClaimIdRoute
  '/d/$code': typeof DCodeRoute
  '/e/$code': typeof ECodeRoute
  '/embed/address': typeof EmbedAddressRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/checkout-component': typeof CheckoutComponentRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/for-business': typeof ForBusinessRoute
  '/for-couriers': typeof ForCouriersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/offline': typeof OfflineRoute
  '/places': typeof PlacesRoute
  '/plans': typeof PlansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/widget': typeof WidgetRoute
  '/courier': typeof AuthenticatedCourierRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer-dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/my-addresses': typeof AuthenticatedMyAddressesRoute
  '/my-corrections': typeof AuthenticatedMyCorrectionsRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/a/$code': typeof ACodeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/corrections': typeof AdminCorrectionsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/quality': typeof AdminQualityRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$id': typeof ClaimIdRoute
  '/d/$code': typeof DCodeRoute
  '/e/$code': typeof ECodeRoute
  '/embed/address': typeof EmbedAddressRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/checkout-component': typeof CheckoutComponentRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/for-business': typeof ForBusinessRoute
  '/for-couriers': typeof ForCouriersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/offline': typeof OfflineRoute
  '/places': typeof PlacesRoute
  '/plans': typeof PlansRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/widget': typeof WidgetRoute
  '/_authenticated/courier': typeof AuthenticatedCourierRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/developer-dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/_authenticated/my-addresses': typeof AuthenticatedMyAddressesRoute
  '/_authenticated/my-corrections': typeof AuthenticatedMyCorrectionsRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/a/$code': typeof ACodeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/corrections': typeof AdminCorrectionsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/quality': typeof AdminQualityRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$id': typeof ClaimIdRoute
  '/d/$code': typeof DCodeRoute
  '/e/$code': typeof ECodeRoute
  '/embed/address': typeof EmbedAddressRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-reference'
    | '/auth'
    | '/checkout-component'
    | '/contact'
    | '/create'
    | '/developers'
    | '/docs'
    | '/for-business'
    | '/for-couriers'
    | '/how-it-works'
    | '/offline'
    | '/places'
    | '/plans'
    | '/privacy-policy'
    | '/scan'
    | '/search'
    | '/terms'
    | '/widget'
    | '/courier'
    | '/dashboard'
    | '/developer-dashboard'
    | '/my-addresses'
    | '/my-corrections'
    | '/privacy'
    | '/vault'
    | '/verify'
    | '/a/$code'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/claims'
    | '/admin/corrections'
    | '/admin/navigation'
    | '/admin/plans'
    | '/admin/quality'
    | '/business/$id'
    | '/claim/$id'
    | '/d/$code'
    | '/e/$code'
    | '/embed/address'
    | '/navigation/$code'
    | '/t/$token'
    | '/admin/'
    | '/api/public/checkout'
    | '/api/public/resolve'
    | '/api/v1/$'
    | '/api/public/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-reference'
    | '/auth'
    | '/checkout-component'
    | '/contact'
    | '/create'
    | '/developers'
    | '/docs'
    | '/for-business'
    | '/for-couriers'
    | '/how-it-works'
    | '/offline'
    | '/places'
    | '/plans'
    | '/privacy-policy'
    | '/scan'
    | '/search'
    | '/terms'
    | '/widget'
    | '/courier'
    | '/dashboard'
    | '/developer-dashboard'
    | '/my-addresses'
    | '/my-corrections'
    | '/privacy'
    | '/vault'
    | '/verify'
    | '/a/$code'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/claims'
    | '/admin/corrections'
    | '/admin/navigation'
    | '/admin/plans'
    | '/admin/quality'
    | '/business/$id'
    | '/claim/$id'
    | '/d/$code'
    | '/e/$code'
    | '/embed/address'
    | '/navigation/$code'
    | '/t/$token'
    | '/admin'
    | '/api/public/checkout'
    | '/api/public/resolve'
    | '/api/v1/$'
    | '/api/public/v1/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/api-reference'
    | '/auth'
    | '/checkout-component'
    | '/contact'
    | '/create'
    | '/developers'
    | '/docs'
    | '/for-business'
    | '/for-couriers'
    | '/how-it-works'
    | '/offline'
    | '/places'
    | '/plans'
    | '/privacy-policy'
    | '/scan'
    | '/search'
    | '/terms'
    | '/widget'
    | '/_authenticated/courier'
    | '/_authenticated/dashboard'
    | '/_authenticated/developer-dashboard'
    | '/_authenticated/my-addresses'
    | '/_authenticated/my-corrections'
    | '/_authenticated/privacy'
    | '/_authenticated/vault'
    | '/_authenticated/verify'
    | '/a/$code'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/claims'
    | '/admin/corrections'
    | '/admin/navigation'
    | '/admin/plans'
    | '/admin/quality'
    | '/business/$id'
    | '/claim/$id'
    | '/d/$code'
    | '/e/$code'
    | '/embed/address'
    | '/navigation/$code'
    | '/t/$token'
    | '/admin/'
    | '/api/public/checkout'
    | '/api/public/resolve'
    | '/api/v1/$'
    | '/api/public/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  AuthRoute: typeof AuthRoute
  CheckoutComponentRoute: typeof CheckoutComponentRoute
  ContactRoute: typeof ContactRoute
  CreateRoute: typeof CreateRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  ForBusinessRoute: typeof ForBusinessRoute
  ForCouriersRoute: typeof ForCouriersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OfflineRoute: typeof OfflineRoute
  PlacesRoute: typeof PlacesRoute
  PlansRoute: typeof PlansRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  WidgetRoute: typeof WidgetRoute
  ACodeRoute: typeof ACodeRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminCorrectionsRoute: typeof AdminCorrectionsRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminQualityRoute: typeof AdminQualityRoute
  BusinessIdRoute: typeof BusinessIdRoute
  ClaimIdRoute: typeof ClaimIdRoute
  DCodeRoute: typeof DCodeRoute
  ECodeRoute: typeof ECodeRoute
  EmbedAddressRoute: typeof EmbedAddressRoute
  NavigationCodeRoute: typeof NavigationCodeRoute
  TTokenRoute: typeof TTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicResolveRoute: typeof ApiPublicResolveRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-component': {
      id: '/checkout-component'
      path: '/checkout-component'
      fullPath: '/checkout-component'
      preLoaderRoute: typeof CheckoutComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-business': {
      id: '/for-business'
      path: '/for-business'
      fullPath: '/for-business'
      preLoaderRoute: typeof ForBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-couriers': {
      id: '/for-couriers'
      path: '/for-couriers'
      fullPath: '/for-couriers'
      preLoaderRoute: typeof ForCouriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courier': {
      id: '/_authenticated/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof AuthenticatedCourierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer-dashboard': {
      id: '/_authenticated/developer-dashboard'
      path: '/developer-dashboard'
      fullPath: '/developer-dashboard'
      preLoaderRoute: typeof AuthenticatedDeveloperDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-addresses': {
      id: '/_authenticated/my-addresses'
      path: '/my-addresses'
      fullPath: '/my-addresses'
      preLoaderRoute: typeof AuthenticatedMyAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-corrections': {
      id: '/_authenticated/my-corrections'
      path: '/my-corrections'
      fullPath: '/my-corrections'
      preLoaderRoute: typeof AuthenticatedMyCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$code': {
      id: '/a/$code'
      path: '/a/$code'
      fullPath: '/a/$code'
      preLoaderRoute: typeof ACodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/admin/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/corrections': {
      id: '/admin/corrections'
      path: '/admin/corrections'
      fullPath: '/admin/corrections'
      preLoaderRoute: typeof AdminCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/admin/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quality': {
      id: '/admin/quality'
      path: '/admin/quality'
      fullPath: '/admin/quality'
      preLoaderRoute: typeof AdminQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$id': {
      id: '/claim/$id'
      path: '/claim/$id'
      fullPath: '/claim/$id'
      preLoaderRoute: typeof ClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$code': {
      id: '/d/$code'
      path: '/d/$code'
      fullPath: '/d/$code'
      preLoaderRoute: typeof DCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$code': {
      id: '/e/$code'
      path: '/e/$code'
      fullPath: '/e/$code'
      preLoaderRoute: typeof ECodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/address': {
      id: '/embed/address'
      path: '/embed/address'
      fullPath: '/embed/address'
      preLoaderRoute: typeof EmbedAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation/$code': {
      id: '/navigation/$code'
      path: '/navigation/$code'
      fullPath: '/navigation/$code'
      preLoaderRoute: typeof NavigationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resolve': {
      id: '/api/public/resolve'
      path: '/api/public/resolve'
      fullPath: '/api/public/resolve'
      preLoaderRoute: typeof ApiPublicResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCourierRoute: typeof AuthenticatedCourierRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeveloperDashboardRoute: typeof AuthenticatedDeveloperDashboardRoute
  AuthenticatedMyAddressesRoute: typeof AuthenticatedMyAddressesRoute
  AuthenticatedMyCorrectionsRoute: typeof AuthenticatedMyCorrectionsRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCourierRoute: AuthenticatedCourierRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeveloperDashboardRoute: AuthenticatedDeveloperDashboardRoute,
  AuthenticatedMyAddressesRoute: AuthenticatedMyAddressesRoute,
  AuthenticatedMyCorrectionsRoute: AuthenticatedMyCorrectionsRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  AuthRoute: AuthRoute,
  CheckoutComponentRoute: CheckoutComponentRoute,
  ContactRoute: ContactRoute,
  CreateRoute: CreateRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  ForBusinessRoute: ForBusinessRoute,
  ForCouriersRoute: ForCouriersRoute,
  HowItWorksRoute: HowItWorksRoute,
  OfflineRoute: OfflineRoute,
  PlacesRoute: PlacesRoute,
  PlansRoute: PlansRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  WidgetRoute: WidgetRoute,
  ACodeRoute: ACodeRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminCorrectionsRoute: AdminCorrectionsRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminQualityRoute: AdminQualityRoute,
  BusinessIdRoute: BusinessIdRoute,
  ClaimIdRoute: ClaimIdRoute,
  DCodeRoute: DCodeRoute,
  ECodeRoute: ECodeRoute,
  EmbedAddressRoute: EmbedAddressRoute,
  NavigationCodeRoute: NavigationCodeRoute,
  TTokenRoute: TTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicResolveRoute: ApiPublicResolveRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
