/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutComponentRouteImport } from './routes/checkout-component'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as MyAddressesRouteImport } from './routes/my-addresses'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as ACodeRouteImport } from './routes/a.$code'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as BusinessIdRouteImport } from './routes/business.$id'
import { Route as ClaimIdRouteImport } from './routes/claim.$id'
import { Route as DCodeRouteImport } from './routes/d.$code'
import { Route as ECodeRouteImport } from './routes/e.$code'
import { Route as EmbedAddressRouteImport } from './routes/embed.address'
import { Route as NavigationCodeRouteImport } from './routes/navigation.$code'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api.public.checkout'
import { Route as ApiPublicResolveRouteImport } from './routes/api.public.resolve'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api.public.v1.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutComponentRoute = CheckoutComponentRouteImport.update({
  id: '/checkout-component',
  path: '/checkout-component',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAddressesRoute = MyAddressesRouteImport.update({
  id: '/my-addresses',
  path: '/my-addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ACodeRoute = ACodeRouteImport.update({
  id: '/a/$code',
  path: '/a/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIdRoute = ClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DCodeRoute = DCodeRouteImport.update({
  id: '/d/$code',
  path: '/d/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ECodeRoute = ECodeRouteImport.update({
  id: '/e/$code',
  path: '/e/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedAddressRoute = EmbedAddressRouteImport.update({
  id: '/embed/address',
  path: '/embed/address',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationCodeRoute = NavigationCodeRouteImport.update({
  id: '/navigation/$code',
  path: '/navigation/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResolveRoute = ApiPublicResolveRouteImport.update({
  id: '/api/public/resolve',
  path: '/api/public/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/checkout-component': typeof CheckoutComponentRoute
  '/courier': typeof CourierRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/my-addresses': typeof MyAddressesRoute
  '/search': typeof SearchRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/widget': typeof WidgetRoute
  '/a/$code': typeof ACodeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$id': typeof ClaimIdRoute
  '/d/$code': typeof DCodeRoute
  '/e/$code': typeof ECodeRoute
  '/embed/address': typeof EmbedAddressRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/checkout-component': typeof CheckoutComponentRoute
  '/courier': typeof CourierRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/my-addresses': typeof MyAddressesRoute
  '/search': typeof SearchRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/widget': typeof WidgetRoute
  '/a/$code': typeof ACodeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$id': typeof ClaimIdRoute
  '/d/$code': typeof DCodeRoute
  '/e/$code': typeof ECodeRoute
  '/embed/address': typeof EmbedAddressRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/checkout-component': typeof CheckoutComponentRoute
  '/courier': typeof CourierRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/my-addresses': typeof MyAddressesRoute
  '/search': typeof SearchRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/widget': typeof WidgetRoute
  '/a/$code': typeof ACodeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$id': typeof ClaimIdRoute
  '/d/$code': typeof DCodeRoute
  '/e/$code': typeof ECodeRoute
  '/embed/address': typeof EmbedAddressRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-reference'
    | '/auth'
    | '/checkout-component'
    | '/courier'
    | '/create'
    | '/dashboard'
    | '/developers'
    | '/docs'
    | '/my-addresses'
    | '/search'
    | '/vault'
    | '/verify'
    | '/widget'
    | '/a/$code'
    | '/admin/audit'
    | '/admin/claims'
    | '/admin/navigation'
    | '/business/$id'
    | '/claim/$id'
    | '/d/$code'
    | '/e/$code'
    | '/embed/address'
    | '/navigation/$code'
    | '/t/$token'
    | '/api/public/checkout'
    | '/api/public/resolve'
    | '/api/v1/$'
    | '/api/public/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-reference'
    | '/auth'
    | '/checkout-component'
    | '/courier'
    | '/create'
    | '/dashboard'
    | '/developers'
    | '/docs'
    | '/my-addresses'
    | '/search'
    | '/vault'
    | '/verify'
    | '/widget'
    | '/a/$code'
    | '/admin/audit'
    | '/admin/claims'
    | '/admin/navigation'
    | '/business/$id'
    | '/claim/$id'
    | '/d/$code'
    | '/e/$code'
    | '/embed/address'
    | '/navigation/$code'
    | '/t/$token'
    | '/api/public/checkout'
    | '/api/public/resolve'
    | '/api/v1/$'
    | '/api/public/v1/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-reference'
    | '/auth'
    | '/checkout-component'
    | '/courier'
    | '/create'
    | '/dashboard'
    | '/developers'
    | '/docs'
    | '/my-addresses'
    | '/search'
    | '/vault'
    | '/verify'
    | '/widget'
    | '/a/$code'
    | '/admin/audit'
    | '/admin/claims'
    | '/admin/navigation'
    | '/business/$id'
    | '/claim/$id'
    | '/d/$code'
    | '/e/$code'
    | '/embed/address'
    | '/navigation/$code'
    | '/t/$token'
    | '/api/public/checkout'
    | '/api/public/resolve'
    | '/api/v1/$'
    | '/api/public/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiReferenceRoute: typeof ApiReferenceRoute
  AuthRoute: typeof AuthRoute
  CheckoutComponentRoute: typeof CheckoutComponentRoute
  CourierRoute: typeof CourierRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  MyAddressesRoute: typeof MyAddressesRoute
  SearchRoute: typeof SearchRoute
  VaultRoute: typeof VaultRoute
  VerifyRoute: typeof VerifyRoute
  WidgetRoute: typeof WidgetRoute
  ACodeRoute: typeof ACodeRoute
  BusinessIdRoute: typeof BusinessIdRoute
  ClaimIdRoute: typeof ClaimIdRoute
  DCodeRoute: typeof DCodeRoute
  ECodeRoute: typeof ECodeRoute
  EmbedAddressRoute: typeof EmbedAddressRoute
  NavigationCodeRoute: typeof NavigationCodeRoute
  TTokenRoute: typeof TTokenRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicResolveRoute: typeof ApiPublicResolveRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-component': {
      id: '/checkout-component'
      path: '/checkout-component'
      fullPath: '/checkout-component'
      preLoaderRoute: typeof CheckoutComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-addresses': {
      id: '/my-addresses'
      path: '/my-addresses'
      fullPath: '/my-addresses'
      preLoaderRoute: typeof MyAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$code': {
      id: '/a/$code'
      path: '/a/$code'
      fullPath: '/a/$code'
      preLoaderRoute: typeof ACodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$id': {
      id: '/claim/$id'
      path: '/claim/$id'
      fullPath: '/claim/$id'
      preLoaderRoute: typeof ClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$code': {
      id: '/d/$code'
      path: '/d/$code'
      fullPath: '/d/$code'
      preLoaderRoute: typeof DCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$code': {
      id: '/e/$code'
      path: '/e/$code'
      fullPath: '/e/$code'
      preLoaderRoute: typeof ECodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/address': {
      id: '/embed/address'
      path: '/embed/address'
      fullPath: '/embed/address'
      preLoaderRoute: typeof EmbedAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation/$code': {
      id: '/navigation/$code'
      path: '/navigation/$code'
      fullPath: '/navigation/$code'
      preLoaderRoute: typeof NavigationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resolve': {
      id: '/api/public/resolve'
      path: '/api/public/resolve'
      fullPath: '/api/public/resolve'
      preLoaderRoute: typeof ApiPublicResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminNavigationRoute: AdminNavigationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiReferenceRoute: ApiReferenceRoute,
  AuthRoute: AuthRoute,
  CheckoutComponentRoute: CheckoutComponentRoute,
  CourierRoute: CourierRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  MyAddressesRoute: MyAddressesRoute,
  SearchRoute: SearchRoute,
  VaultRoute: VaultRoute,
  VerifyRoute: VerifyRoute,
  WidgetRoute: WidgetRoute,
  ACodeRoute: ACodeRoute,
  BusinessIdRoute: BusinessIdRoute,
  ClaimIdRoute: ClaimIdRoute,
  DCodeRoute: DCodeRoute,
  ECodeRoute: ECodeRoute,
  EmbedAddressRoute: EmbedAddressRoute,
  NavigationCodeRoute: NavigationCodeRoute,
  TTokenRoute: TTokenRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicResolveRoute: ApiPublicResolveRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
