/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as MyAddressesRouteImport } from './routes/my-addresses'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as BusinessIdRouteImport } from './routes/business.$id'
import { Route as NavigationCodeRouteImport } from './routes/navigation.$code'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as ApiPublicResolveRouteImport } from './routes/api.public.resolve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAddressesRoute = MyAddressesRouteImport.update({
  id: '/my-addresses',
  path: '/my-addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationCodeRoute = NavigationCodeRouteImport.update({
  id: '/navigation/$code',
  path: '/navigation/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResolveRoute = ApiPublicResolveRouteImport.update({
  id: '/api/public/resolve',
  path: '/api/public/resolve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/courier': typeof CourierRoute
  '/create': typeof CreateRoute
  '/developers': typeof DevelopersRoute
  '/my-addresses': typeof MyAddressesRoute
  '/search': typeof SearchRoute
  '/verify': typeof VerifyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/business/$id': typeof BusinessIdRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/courier': typeof CourierRoute
  '/create': typeof CreateRoute
  '/developers': typeof DevelopersRoute
  '/my-addresses': typeof MyAddressesRoute
  '/search': typeof SearchRoute
  '/verify': typeof VerifyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/business/$id': typeof BusinessIdRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/courier': typeof CourierRoute
  '/create': typeof CreateRoute
  '/developers': typeof DevelopersRoute
  '/my-addresses': typeof MyAddressesRoute
  '/search': typeof SearchRoute
  '/verify': typeof VerifyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/business/$id': typeof BusinessIdRoute
  '/navigation/$code': typeof NavigationCodeRoute
  '/t/$token': typeof TTokenRoute
  '/api/public/resolve': typeof ApiPublicResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/courier'
    | '/create'
    | '/developers'
    | '/my-addresses'
    | '/search'
    | '/verify'
    | '/admin/audit'
    | '/admin/navigation'
    | '/business/$id'
    | '/navigation/$code'
    | '/t/$token'
    | '/api/public/resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/courier'
    | '/create'
    | '/developers'
    | '/my-addresses'
    | '/search'
    | '/verify'
    | '/admin/audit'
    | '/admin/navigation'
    | '/business/$id'
    | '/navigation/$code'
    | '/t/$token'
    | '/api/public/resolve'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/courier'
    | '/create'
    | '/developers'
    | '/my-addresses'
    | '/search'
    | '/verify'
    | '/admin/audit'
    | '/admin/navigation'
    | '/business/$id'
    | '/navigation/$code'
    | '/t/$token'
    | '/api/public/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CourierRoute: typeof CourierRoute
  CreateRoute: typeof CreateRoute
  DevelopersRoute: typeof DevelopersRoute
  MyAddressesRoute: typeof MyAddressesRoute
  SearchRoute: typeof SearchRoute
  VerifyRoute: typeof VerifyRoute
  BusinessIdRoute: typeof BusinessIdRoute
  NavigationCodeRoute: typeof NavigationCodeRoute
  TTokenRoute: typeof TTokenRoute
  ApiPublicResolveRoute: typeof ApiPublicResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-addresses': {
      id: '/my-addresses'
      path: '/my-addresses'
      fullPath: '/my-addresses'
      preLoaderRoute: typeof MyAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation/$code': {
      id: '/navigation/$code'
      path: '/navigation/$code'
      fullPath: '/navigation/$code'
      preLoaderRoute: typeof NavigationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resolve': {
      id: '/api/public/resolve'
      path: '/api/public/resolve'
      fullPath: '/api/public/resolve'
      preLoaderRoute: typeof ApiPublicResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminNavigationRoute: AdminNavigationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CourierRoute: CourierRoute,
  CreateRoute: CreateRoute,
  DevelopersRoute: DevelopersRoute,
  MyAddressesRoute: MyAddressesRoute,
  SearchRoute: SearchRoute,
  VerifyRoute: VerifyRoute,
  BusinessIdRoute: BusinessIdRoute,
  NavigationCodeRoute: NavigationCodeRoute,
  TTokenRoute: TTokenRoute,
  ApiPublicResolveRoute: ApiPublicResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
